sh ./certora/scripts/Controller.sh integrityOfCreateLoan
sh ./certora/scripts/Controller.sh integrityOfRepay
sh ./certora/scripts/Controller.sh borrowMoreCumulative
sh ./certora/scripts/Controller.sh noReducerToOther
sh ./certora/scripts/Controller.sh integrityOfLiquidate
sh ./certora/scripts/Controller.sh onlyLiquidateCanDecreaseShares
sh ./certora/scripts/Controller.sh repayCumulative
sh ./certora/scripts/Controller.sh liquidateOnlyIfHealthFactorNegative
sh ./certora/scripts/Controller.sh anyPositionCanBeClosed